import numpy as np
x=np.array([1,5])
y=np.array([3,6])
print("Print original numbers :")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x,y))
print("Comparison - greater_equal")
print(np.greater_equal(x,y))
print("Comparison - equal")
print(np.less(x,y))
print("Comparison - less_equal")
print(np.less_equal(x,y))
